/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInstructorsRouteImport } from './routes/admin.instructors'
import { Route as AdminDirectionsRouteImport } from './routes/admin.directions'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAccountRouteImport } from './routes/admin.account'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstructorsRoute = AdminInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDirectionsRoute = AdminDirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/consent': typeof ConsentRoute
  '/offer': typeof OfferRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/directions': typeof AdminDirectionsRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/offer': typeof OfferRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/directions': typeof AdminDirectionsRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/consent': typeof ConsentRoute
  '/offer': typeof OfferRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/directions': typeof AdminDirectionsRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/consent'
    | '/offer'
    | '/payments'
    | '/privacy'
    | '/admin/account'
    | '/admin/bookings'
    | '/admin/directions'
    | '/admin/instructors'
    | '/admin/login'
    | '/admin/schedule'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/offer'
    | '/payments'
    | '/privacy'
    | '/admin/account'
    | '/admin/bookings'
    | '/admin/directions'
    | '/admin/instructors'
    | '/admin/login'
    | '/admin/schedule'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/consent'
    | '/offer'
    | '/payments'
    | '/privacy'
    | '/admin/account'
    | '/admin/bookings'
    | '/admin/directions'
    | '/admin/instructors'
    | '/admin/login'
    | '/admin/schedule'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  OfferRoute: typeof OfferRoute
  PaymentsRoute: typeof PaymentsRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructors': {
      id: '/admin/instructors'
      path: '/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AdminInstructorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/directions': {
      id: '/admin/directions'
      path: '/directions'
      fullPath: '/admin/directions'
      preLoaderRoute: typeof AdminDirectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDirectionsRoute: typeof AdminDirectionsRoute
  AdminInstructorsRoute: typeof AdminInstructorsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDirectionsRoute: AdminDirectionsRoute,
  AdminInstructorsRoute: AdminInstructorsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConsentRoute: ConsentRoute,
  OfferRoute: OfferRoute,
  PaymentsRoute: PaymentsRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
